### ISSUE TITLE
Building with revision dependencies

### ISSUE THREAD

**Issue by adamchainz** [uber/phabricator-jenkins-plugin#157] opened 2016-05-19 15:33 UTC
`arc patch help` implies that running it on a revision that depends on another should bring in the latest diff from the other, but it doesn't seem to do that.

To support revision-on-revision testing, would it be easy to make the plugin pull in dependency revisions, or would it be better to make `arc patch` to do that?

**Comment by sectioneight** [comment] 2016-05-19 20:12
Potential duplicate of #104

We make this work at Uber by using "Staging Areas" which ensure that the dependent branch/revision is available to apply the patch to. It sounds like `arc` should be intelligent enough to do this for you -- is it not? Do you have some build logs of what happens when you try to use the plugin to do this?

**Comment by adamchainz** [comment] 2016-07-21 15:20
Sorry for no reply, I just got around to trying this. Staging area seems to work, although as the [harbormaster docs note](https://secure.phabricator.com/book/phabricator/article/harbormaster/) they're apparently quite experimental.

One thing I found is that the "Create git branch" flag is required in the plugin for the staging area to work.

I think the README could be updated to mention staging areas.

**Comment by sectioneight** [comment] 2016-07-21 19:02
Yup, I've been holding off on recommending that until it comes out of "experimental" phase, but it's probably time to document it and just put a big fat warning that it's subject to change and not officially supported on the Phabricator side.

**Comment by adamchainz** [comment] 2016-07-27 16:46
Btw do you have a process for removing the staging area tags? Because I've noticed harbormaster doesn't seem to care about removing them at any point

**Comment by sectioneight** [comment] 2016-07-27 17:47
Nope. I assume Phabricator will provide a way to prune them at some point.

**Comment by kageiit** [comment] 2016-08-16 14:41
> Btw do you have a process for removing the staging area tags

We setup a jenkins job to automatically purge tags older than a week and it runs once a week on the repos on which we have staging areas configured

**Comment by adamchainz** [comment] 2016-08-16 15:35
> We setup a jenkins job to automatically purge tags older than a week and it runs once a week on the repos on which we have staging areas configured

Sweet. Got a bash one liner you can share? 😸

**Comment by kageiit** [comment] 2016-08-16 15:49
> Sweet. Got a bash one liner you can share? 😸

I dont think its a one liner. It involves some logic which talks to phab api and uses some other git commands to get staging area refs within a timeframe and deletes them.

**Comment by adamchainz** [comment] 2016-08-16 16:07
Oh okay fair.

**Comment by sectioneight** [comment] 2016-09-26 00:32
@adamchainz @kageiit is there something to be done here from the plugin side? Seems like this is a phabricator/tag cruft thing that we don't have any control over. If there's something we can implement, please re-open and let me know.

**Closed by sectioneight** 2016-09-26 00:32 UTC

**Comment by adamchainz** [comment] 2016-09-26 07:24
Maybe document the potential for staging areas, despite their 'experimental' status?

**Comment by sectioneight** [comment] 2016-09-26 14:34
Good call, will overhaul docs in #154
