### ISSUE TITLE
Jenkins build fails when applying patch

### ISSUE THREAD

**Issue by zegl** [uber/phabricator-jenkins-plugin#109] opened 2015-11-18 16:41 UTC
I've been trying to integrate Phabricator with our Jenkins server without success. The output (in Jenkins) before the build fails is this:

```
[hidden] $ /home/jenkins/phabricator/arcanist/bin/arc patch --nobranch --diff 204 ********
Exception
 Select a Default Commit Range 

You're running a command which operates on a range of revisions (usually,
from some revision to HEAD) but have not specified the revision that should
determine the start of the range.

Previously, arc assumed you meant 'HEAD^' when you did not specify a start
revision, but this behavior does not make much sense in most workflows
outside of Facebook's historic git-svn workflow.

arc no longer assumes 'HEAD^'. You must specify a relative commit explicitly
when you invoke a command (e.g., `arc diff HEAD^`, not just `arc diff`) or
select a default for this working copy.

In most cases, the best default is 'origin/master'. You can also select
'HEAD^' to preserve the old behavior, or some other remote or branch. But you
almost certainly want to select 'origin/master'.

(Technically: the merge-base of the selected revision and HEAD is used to
determine the start of the commit range.)

    What default do you want to use? [origin/master] The program is attempting to read user input, but stdin is being piped from some other source (not a TTY).
(Run with `--trace` for a full exception trace.)
[phabricator:arcanist] Error applying arc patch; got non-zero exit code FAILURE
[phabricator:process-build-result] No unit results available.
[phabricator:process-build-result] No coverage provider available.
```

I am running the [latest version](https://github.com/phacility/arcanist/commit/e3e232530c6e9393228cdd246ba9f4a48c0f5917) of anarcist, so that should not be the issue.

Any ideas?

**Comment by sectioneight** [comment] 2015-11-18 17:55
Hmm... I feel like I've seen that prompt from arcanist locally, but never or jenkins. What happens if you run the same command (without the *** part) on your own working copy?

It also doesn't really make sense that arc would need a commit range for patch, which should apply the downloaded patch to the working copy.

Do you have any other steps to reproduce?

**Comment by sectioneight** [comment] 2016-01-19 21:48
Are you having issues with this still? Any thoughts on my questions above?

**Comment by zegl** [comment] 2016-01-20 09:14
I never got it to work correctly with your plugin, so we're applying the patches with a bash script instead.

**Comment by Treri** [comment] 2016-01-20 09:29
@zegl have you set git-plugin correctly?

I follow the steps on jenkins plugins page and setup this plugin to work successfully.

**Comment by sectioneight** [comment] 2016-01-27 18:11
Closing due to inability to reproduce.

**Comment by vswamy** [comment] 2016-07-20 23:56
I am also seeing this on Jenkins. Any thougths?

**Comment by sectioneight** [comment] 2016-07-21 00:03
Discussed offline, this is a job misconfiguration not an issue with the plugin.

**Closed** 2016-07-21 00:02 UTC

**Comment by RaviKishoreKota** [comment] 2017-03-30 16:24
Hi I am trying to configure Phabricator with Jenkins getting below error message on Jenkins log any help?


[phabricator:uberalls] No cobertura results found
com.uber.jenkins.phabricator.conduit.ConduitAPIException: Unable to find 'R3:169' key in 'result': (null object) null
	at com.uber.jenkins.phabricator.conduit.DifferentialClient.fetchDiff(DifferentialClient.java:85)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:165)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
[phabricator:conduit] Unable to fetch differential from Conduit API
[phabricator:conduit] Unable to find 'R3:169' key in 'result': (null object) null

**Comment by RaviKishoreKota** [comment] 2017-03-30 16:25
Arcanist is mandatory to install on build server?
